parameters:
  - name: testParam
    type: string
    default: 'N/A'
trigger:
- main
# pool:
#   vmImage: 'ubuntu-latest'
pool: AZP-Pool
extends:
  template: hello-template.yml
  parameters:
    testParam: ${{ parameters.testParam }}

- job: build_Oregon
  variables:
  - group: hello-001
  steps:
    - script: |
        echo $foo
        echo $hello
      displayName: 'Show Variable Values'