parameters:
  - name: testParam
    type: string
    default: 'N/A'
trigger:
- main
# pool:
#   vmImage: 'ubuntu-latest'
pool: AZP-Pool
extends:
  template: group-template.yml
  parameters:
    testParam: ${{ parameters.testParam }}

